version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore DataTablePlus.sln
build:
  project: DataTablePlus.sln
  verbosity: minimal
test: off